/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c912f208-7b14-4cc5-8cbc-5d87cbae9ba9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X7tgWFrep",
    "aws_user_pools_web_client_id": "1p31hn3ddjafl6ubh4h5kph49l",
    "oauth": {}
};


export default awsmobile;
