/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c912f208-7b14-4cc5-8cbc-5d87cbae9ba9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X7tgWFrep",
    "aws_user_pools_web_client_id": "1p31hn3ddjafl6ubh4h5kph49l",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://potw5xbva5dmvf5lzgeybomo5y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zcdb5c3yprhq3oziq2f246ixaq"
};


export default awsmobile;
